apiVersion: v1
kind: Service
metadata:
  name: example-svc-name
  namespace: example-ns
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: gradle-test
  type: NodePort

